# -*- coding: utf-8 -*-
"""DetR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJetwww14jwm6LmVDvbUv56rFrkg-N3h

Install the necessary libraries:
"""

# !pip install transformers
# !pip install timm

"""Import the pipeline abstraction:"""

from transformers import pipeline

"""Create object detection pipeline using DetR with ResNet-50 backend:"""

obj_detection_pipeline = pipeline(
    task="object-detection",
    model="facebook/detr-resnet-50")

"""Display the model definition:"""

print(obj_detection_pipeline.model)

"""Detect objects in a image:"""

obj_detection_pipeline("https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Left_side_of_Flying_Pigeon.jpg/640px-Left_side_of_Flying_Pigeon.jpg")

"""Create segmentation pipeline instance with DetR Resnet-50 backend:"""

segmentation_pipeline = pipeline(
    task="image-segmentation",
    model="facebook/detr-resnet-50-panoptic")

"""Display the segmentation model definition:"""

print(segmentation_pipeline.model)

"""Segment an image:"""

segmentation_pipeline("https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Left_side_of_Flying_Pigeon.jpg/640px-Left_side_of_Flying_Pigeon.jpg")