# -*- coding: utf-8 -*-
"""stable_diffusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QFlG3wN6QLBuDizamnk6BrWUbBluJATZ

```
# This is formatted as code
```

Install the necessary packages:
"""

# !pip install transformers
# !pip install diffusers
# !pip install accelerate

"""Do the imports:"""

import torch
from diffusers import StableDiffusionPipeline

"""Instantiate the stable diffusion pipeline. We'll use SD 2.1:"""

sd_pipe = StableDiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1",
    torch_dtype=torch.float16)

sd_pipe.to('cuda')

"""Print the models:"""

print(sd_pipe.tokenizer)

print(sd_pipe.vae)

print(sd_pipe.unet)

print(sd_pipe.text_encoder)

print(sd_pipe.scheduler)

"""Let's generate an image from text:"""

prompt = \
  "High quality photo of a racing car on a track"
image = sd_pipe(
    prompt,
    num_inference_steps=100).images[0]

"""Display the image:"""

from matplotlib import pyplot as plt
plt.imshow(image)
plt.axis("off")
plt.show()