# -*- coding: utf-8 -*-
"""stable_diffusion_xl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXBvZekJt8G__6z8HwTcuIy8vjcNXFIZ

Install the necessary packages:
"""

# !pip install transformers
# !pip install diffusers
# !pip install accelerate

"""Do the imports:"""

import torch
from diffusers import StableDiffusionXLPipeline

"""Instantiate the stable diffusion pipeline. We'll use SD 2.1:"""

sd_pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16)

sd_pipe.to('cuda')

"""Print the models:"""

print(sd_pipe.vae)

print(sd_pipe.unet)

print(sd_pipe.text_encoder)

"""Let's generate an image from text:"""

prompt = "High quality photo of a racing car on a track"
image = sd_pipe(prompt, num_inference_steps=100).images[0]

"""Display the image:"""

from matplotlib import pyplot as plt
plt.imshow(image)
plt.axis("off")
plt.show()