# -*- coding: utf-8 -*-
"""Vision Transformer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gnduDoa3jRPaqJI3tZ1bUON1Cv-FZ9X

Install the transformers library:
"""

# !pip install transformers

"""Import the `pipeline` abstraction:"""

from transformers import pipeline

"""Create the image classification pipeline:"""

img_classification_pipeline = pipeline(
    task="image-classification",
    model="google/vit-base-patch16-224")

print(img_classification_pipeline.model)

"""Classify an image:"""

img_classification_pipeline("https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Left_side_of_Flying_Pigeon.jpg/640px-Left_side_of_Flying_Pigeon.jpg")